***INCLUDE LJSS3st1 .
*
*     Interne Tabellen für den Aufruf des Funktionsbausteines
*     'ISP_SELECT_ADDRESS'
*
DATA: BEGIN OF ITAB_JGTSADR OCCURS 20.
        INCLUDE STRUCTURE JGTSADR.
DATA: END OF ITAB_JGTSADR.
*
DATA: BEGIN OF ORT_UPDA_TAB  OCCURS  0.
        INCLUDE  STRUCTURE  JSTORTUPDA.
DATA: END OF ORT_UPDA_TAB.

DATA: BEGIN OF OTL_UPDA_TAB  OCCURS  0.
        INCLUDE  STRUCTURE  JSTOTLUPDA.
DATA: END OF OTL_UPDA_TAB.

DATA: BEGIN OF KGS_UPDA_TAB  OCCURS  0.
        INCLUDE  STRUCTURE  JSTKGSUPDA.
DATA: END OF KGS_UPDA_TAB.

DATA: BEGIN OF PLZ_UPDA_TAB  OCCURS  0.
        INCLUDE  STRUCTURE  JSTPLZUPDA.
DATA: END OF PLZ_UPDA_TAB.

DATA: BEGIN OF PLO_UPDA_TAB  OCCURS  0.
        INCLUDE  STRUCTURE  JSTPLOUPDA.
DATA: END OF PLO_UPDA_TAB.

DATA: BEGIN OF POF_UPDA_TAB  OCCURS  0.
        INCLUDE  STRUCTURE  JSTPOFUPDA.
DATA: END OF POF_UPDA_TAB.

DATA: BEGIN OF STR_UPDA_TAB  OCCURS  0.
        INCLUDE  STRUCTURE  JSTSTRUPDA.
DATA: END OF STR_UPDA_TAB.

 DATA: BEGIN OF UPD_TAB_STRUCTURE,
         ADRNR       LIKE  JGTSADR-ADRNR,
         LOGADR      LIKE  JGTADRA-LOGADR,
         ADRZA       LIKE  JGTADRA-ADRZA,
         LAND1       LIKE  JSTORTUPDA-LAND1,
         ALORT       LIKE  JSTORTUPDA-ALORT,
         STRASSENNR  LIKE  JSTSTRUPDA-STRASSENNR,
         PLZNEU      LIKE  JSTPLZUPDA-PLZNEU,
         GUELTIGAB   LIKE  JSTORTUPDA-GUELTIGAB,
         GUELTIGBIS  LIKE  JSTORTUPDA-GUELTIGBIS,
       END  OF  UPD_TAB_STRUCTURE.

 DATA: UPD_TAB  LIKE  UPD_TAB_STRUCTURE  OCCURS 10  WITH  HEADER LINE.
